version: "3"
services:
  s3:
    image: minio/minio:latest
    container_name: minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  database:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

  envoy:
    image: envoy-v1
    container_name: envoy
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"
      - "8081:8081"

  scraper:
    image: scraper-v1
    container_name: scraper
    environment:
      S3_HOST: http://s3:9000
      S3_USERNAME: ${S3_USERNAME}
      S3_PASSWORD: ${S3_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database
    ports:
      - "55051:55051"

# dc exec database pg_dump -U $POSTGRES_USER novel_database --schema-only
# sqlboiler -c schemas/sqlboiler.toml psql
# psql databasename < data_base_dump