version: "3"
services:
  s3:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data

  database:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/

# dc exec database pg_dump -U $POSTGRES_USER novel_database --schema-only
