// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: novel.proto

package novelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NovelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovelName   string `protobuf:"bytes,1,opt,name=novel_name,json=novelName,proto3" json:"novel_name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Author      string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	NbChapter   int64  `protobuf:"varint,4,opt,name=nb_chapter,json=nbChapter,proto3" json:"nb_chapter,omitempty"`
	Cover       []byte `protobuf:"bytes,5,opt,name=cover,proto3,oneof" json:"cover,omitempty"`
}

func (x *NovelData) Reset() {
	*x = NovelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NovelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NovelData) ProtoMessage() {}

func (x *NovelData) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NovelData.ProtoReflect.Descriptor instead.
func (*NovelData) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{0}
}

func (x *NovelData) GetNovelName() string {
	if x != nil {
		return x.NovelName
	}
	return ""
}

func (x *NovelData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NovelData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *NovelData) GetNbChapter() int64 {
	if x != nil {
		return x.NbChapter
	}
	return 0
}

func (x *NovelData) GetCover() []byte {
	if x != nil {
		return x.Cover
	}
	return nil
}

type GetNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovelName    string `protobuf:"bytes,1,opt,name=novel_name,json=novelName,proto3" json:"novel_name,omitempty"`
	StartChapter *int64 `protobuf:"varint,2,opt,name=start_chapter,json=startChapter,proto3,oneof" json:"start_chapter,omitempty"`
	EndChapter   *int64 `protobuf:"varint,3,opt,name=end_chapter,json=endChapter,proto3,oneof" json:"end_chapter,omitempty"`
}

func (x *GetNovelRequest) Reset() {
	*x = GetNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelRequest) ProtoMessage() {}

func (x *GetNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelRequest.ProtoReflect.Descriptor instead.
func (*GetNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{1}
}

func (x *GetNovelRequest) GetNovelName() string {
	if x != nil {
		return x.NovelName
	}
	return ""
}

func (x *GetNovelRequest) GetStartChapter() int64 {
	if x != nil && x.StartChapter != nil {
		return *x.StartChapter
	}
	return 0
}

func (x *GetNovelRequest) GetEndChapter() int64 {
	if x != nil && x.EndChapter != nil {
		return *x.EndChapter
	}
	return 0
}

type GetNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Novel [][]byte `protobuf:"bytes,1,rep,name=novel,proto3" json:"novel,omitempty"`
}

func (x *GetNovelResponse) Reset() {
	*x = GetNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelResponse) ProtoMessage() {}

func (x *GetNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelResponse.ProtoReflect.Descriptor instead.
func (*GetNovelResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{2}
}

func (x *GetNovelResponse) GetNovel() [][]byte {
	if x != nil {
		return x.Novel
	}
	return nil
}

type ListNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListNovelRequest) Reset() {
	*x = ListNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelRequest) ProtoMessage() {}

func (x *ListNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelRequest.ProtoReflect.Descriptor instead.
func (*ListNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{3}
}

type ListNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Novels []*NovelData `protobuf:"bytes,1,rep,name=novels,proto3" json:"novels,omitempty"`
}

func (x *ListNovelResponse) Reset() {
	*x = ListNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelResponse) ProtoMessage() {}

func (x *ListNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelResponse.ProtoReflect.Descriptor instead.
func (*ListNovelResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{4}
}

func (x *ListNovelResponse) GetNovels() []*NovelData {
	if x != nil {
		return x.Novels
	}
	return nil
}

type RequestNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovelName string `protobuf:"bytes,1,opt,name=novel_name,json=novelName,proto3" json:"novel_name,omitempty"`
}

func (x *RequestNovelRequest) Reset() {
	*x = RequestNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNovelRequest) ProtoMessage() {}

func (x *RequestNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNovelRequest.ProtoReflect.Descriptor instead.
func (*RequestNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{5}
}

func (x *RequestNovelRequest) GetNovelName() string {
	if x != nil {
		return x.NovelName
	}
	return ""
}

type RequestNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovelName string `protobuf:"bytes,1,opt,name=novel_name,json=novelName,proto3" json:"novel_name,omitempty"`
	// Types that are assignable to StatusOneof:
	//
	//	*RequestNovelResponse_CurrentCollection
	//	*RequestNovelResponse_NovelBuilding
	//	*RequestNovelResponse_Completed
	StatusOneof isRequestNovelResponse_StatusOneof `protobuf_oneof:"status_oneof"`
}

func (x *RequestNovelResponse) Reset() {
	*x = RequestNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNovelResponse) ProtoMessage() {}

func (x *RequestNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNovelResponse.ProtoReflect.Descriptor instead.
func (*RequestNovelResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{6}
}

func (x *RequestNovelResponse) GetNovelName() string {
	if x != nil {
		return x.NovelName
	}
	return ""
}

func (m *RequestNovelResponse) GetStatusOneof() isRequestNovelResponse_StatusOneof {
	if m != nil {
		return m.StatusOneof
	}
	return nil
}

func (x *RequestNovelResponse) GetCurrentCollection() int64 {
	if x, ok := x.GetStatusOneof().(*RequestNovelResponse_CurrentCollection); ok {
		return x.CurrentCollection
	}
	return 0
}

func (x *RequestNovelResponse) GetNovelBuilding() int64 {
	if x, ok := x.GetStatusOneof().(*RequestNovelResponse_NovelBuilding); ok {
		return x.NovelBuilding
	}
	return 0
}

func (x *RequestNovelResponse) GetCompleted() bool {
	if x, ok := x.GetStatusOneof().(*RequestNovelResponse_Completed); ok {
		return x.Completed
	}
	return false
}

type isRequestNovelResponse_StatusOneof interface {
	isRequestNovelResponse_StatusOneof()
}

type RequestNovelResponse_CurrentCollection struct {
	CurrentCollection int64 `protobuf:"varint,2,opt,name=current_collection,json=currentCollection,proto3,oneof"`
}

type RequestNovelResponse_NovelBuilding struct {
	NovelBuilding int64 `protobuf:"varint,3,opt,name=novel_building,json=novelBuilding,proto3,oneof"`
}

type RequestNovelResponse_Completed struct {
	Completed bool `protobuf:"varint,4,opt,name=completed,proto3,oneof"`
}

func (*RequestNovelResponse_CurrentCollection) isRequestNovelResponse_StatusOneof() {}

func (*RequestNovelResponse_NovelBuilding) isRequestNovelResponse_StatusOneof() {}

func (*RequestNovelResponse_Completed) isRequestNovelResponse_StatusOneof() {}

var File_novel_proto protoreflect.FileDescriptor

var file_novel_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e,
	0x6f, 0x76, 0x65, 0x6c, 0x22, 0xa8, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x62, 0x5f, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x6e, 0x62, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x22,
	0xa2, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b,
	0x65, 0x6e, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x01, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x88,
	0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x63, 0x68, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x76, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x22, 0x12,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e,
	0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x73, 0x22, 0x34, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x76, 0x65,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f,
	0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2f, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x11, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x27, 0x0a, 0x0e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x6f, 0x76, 0x65,
	0x6c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x32, 0xdb, 0x01, 0x0a, 0x0b, 0x4e, 0x6f,
	0x76, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74,
	0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12, 0x17, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x76,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x6e, 0x6f,
	0x76, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_novel_proto_rawDescOnce sync.Once
	file_novel_proto_rawDescData = file_novel_proto_rawDesc
)

func file_novel_proto_rawDescGZIP() []byte {
	file_novel_proto_rawDescOnce.Do(func() {
		file_novel_proto_rawDescData = protoimpl.X.CompressGZIP(file_novel_proto_rawDescData)
	})
	return file_novel_proto_rawDescData
}

var file_novel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_novel_proto_goTypes = []interface{}{
	(*NovelData)(nil),            // 0: novel.NovelData
	(*GetNovelRequest)(nil),      // 1: novel.GetNovelRequest
	(*GetNovelResponse)(nil),     // 2: novel.GetNovelResponse
	(*ListNovelRequest)(nil),     // 3: novel.ListNovelRequest
	(*ListNovelResponse)(nil),    // 4: novel.ListNovelResponse
	(*RequestNovelRequest)(nil),  // 5: novel.RequestNovelRequest
	(*RequestNovelResponse)(nil), // 6: novel.RequestNovelResponse
}
var file_novel_proto_depIdxs = []int32{
	0, // 0: novel.ListNovelResponse.novels:type_name -> novel.NovelData
	1, // 1: novel.NovelServer.GetNovel:input_type -> novel.GetNovelRequest
	3, // 2: novel.NovelServer.listNovel:input_type -> novel.ListNovelRequest
	5, // 3: novel.NovelServer.RequestNovel:input_type -> novel.RequestNovelRequest
	2, // 4: novel.NovelServer.GetNovel:output_type -> novel.GetNovelResponse
	4, // 5: novel.NovelServer.listNovel:output_type -> novel.ListNovelResponse
	6, // 6: novel.NovelServer.RequestNovel:output_type -> novel.RequestNovelResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_novel_proto_init() }
func file_novel_proto_init() {
	if File_novel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_novel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NovelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_novel_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_novel_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_novel_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*RequestNovelResponse_CurrentCollection)(nil),
		(*RequestNovelResponse_NovelBuilding)(nil),
		(*RequestNovelResponse_Completed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_novel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_novel_proto_goTypes,
		DependencyIndexes: file_novel_proto_depIdxs,
		MessageInfos:      file_novel_proto_msgTypes,
	}.Build()
	File_novel_proto = out.File
	file_novel_proto_rawDesc = nil
	file_novel_proto_goTypes = nil
	file_novel_proto_depIdxs = nil
}
