// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocol/novel.proto

package novelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Chapter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{1}
}

func (x *Chapter) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Chapter) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type PartialNovel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author   string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Summary  string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverURL string   `protobuf:"bytes,5,opt,name=coverURL,proto3" json:"coverURL,omitempty"`
	Genres   []string `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"`
}

func (x *PartialNovel) Reset() {
	*x = PartialNovel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialNovel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialNovel) ProtoMessage() {}

func (x *PartialNovel) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialNovel.ProtoReflect.Descriptor instead.
func (*PartialNovel) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{2}
}

func (x *PartialNovel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartialNovel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PartialNovel) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PartialNovel) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PartialNovel) GetCoverURL() string {
	if x != nil {
		return x.CoverURL
	}
	return ""
}

func (x *PartialNovel) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type FullNovel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Novel     *PartialNovel `protobuf:"bytes,1,opt,name=novel,proto3" json:"novel,omitempty"`
	NbChapter int64         `protobuf:"varint,2,opt,name=nbChapter,proto3" json:"nbChapter,omitempty"`
	Tags      []string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Chapters  []*Chapter    `protobuf:"bytes,4,rep,name=chapters,proto3" json:"chapters,omitempty"`
}

func (x *FullNovel) Reset() {
	*x = FullNovel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullNovel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullNovel) ProtoMessage() {}

func (x *FullNovel) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullNovel.ProtoReflect.Descriptor instead.
func (*FullNovel) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{3}
}

func (x *FullNovel) GetNovel() *PartialNovel {
	if x != nil {
		return x.Novel
	}
	return nil
}

func (x *FullNovel) GetNbChapter() int64 {
	if x != nil {
		return x.NbChapter
	}
	return 0
}

func (x *FullNovel) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FullNovel) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NovelId string   `protobuf:"bytes,1,opt,name=novelId,proto3" json:"novelId,omitempty"`
	Chapter *Chapter `protobuf:"bytes,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *GetBookRequest) GetChapter() *Chapter {
	if x != nil {
		return x.Chapter
	}
	return nil
}

type GetBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetBookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneofIdOrName:
	//
	//	*GetNovelRequest_Id
	//	*GetNovelRequest_Title
	OneofIdOrName isGetNovelRequest_OneofIdOrName `protobuf_oneof:"oneof_id_or_name"`
}

func (x *GetNovelRequest) Reset() {
	*x = GetNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelRequest) ProtoMessage() {}

func (x *GetNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelRequest.ProtoReflect.Descriptor instead.
func (*GetNovelRequest) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{6}
}

func (m *GetNovelRequest) GetOneofIdOrName() isGetNovelRequest_OneofIdOrName {
	if m != nil {
		return m.OneofIdOrName
	}
	return nil
}

func (x *GetNovelRequest) GetId() string {
	if x, ok := x.GetOneofIdOrName().(*GetNovelRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (x *GetNovelRequest) GetTitle() string {
	if x, ok := x.GetOneofIdOrName().(*GetNovelRequest_Title); ok {
		return x.Title
	}
	return ""
}

type isGetNovelRequest_OneofIdOrName interface {
	isGetNovelRequest_OneofIdOrName()
}

type GetNovelRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetNovelRequest_Title struct {
	Title string `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
}

func (*GetNovelRequest_Id) isGetNovelRequest_OneofIdOrName() {}

func (*GetNovelRequest_Title) isGetNovelRequest_OneofIdOrName() {}

type GetNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Novel *FullNovel `protobuf:"bytes,1,opt,name=novel,proto3" json:"novel,omitempty"`
}

func (x *GetNovelResponse) Reset() {
	*x = GetNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelResponse) ProtoMessage() {}

func (x *GetNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelResponse.ProtoReflect.Descriptor instead.
func (*GetNovelResponse) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{7}
}

func (x *GetNovelResponse) GetNovel() *FullNovel {
	if x != nil {
		return x.Novel
	}
	return nil
}

type ListNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartBy *string `protobuf:"bytes,1,opt,name=startBy,proto3,oneof" json:"startBy,omitempty"`
}

func (x *ListNovelRequest) Reset() {
	*x = ListNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelRequest) ProtoMessage() {}

func (x *ListNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelRequest.ProtoReflect.Descriptor instead.
func (*ListNovelRequest) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{8}
}

func (x *ListNovelRequest) GetStartBy() string {
	if x != nil && x.StartBy != nil {
		return *x.StartBy
	}
	return ""
}

type ListNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Novels []*PartialNovel `protobuf:"bytes,1,rep,name=novels,proto3" json:"novels,omitempty"`
}

func (x *ListNovelResponse) Reset() {
	*x = ListNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelResponse) ProtoMessage() {}

func (x *ListNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelResponse.ProtoReflect.Descriptor instead.
func (*ListNovelResponse) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{9}
}

func (x *ListNovelResponse) GetNovels() []*PartialNovel {
	if x != nil {
		return x.Novels
	}
	return nil
}

type RequestNovelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *RequestNovelRequest) Reset() {
	*x = RequestNovelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNovelRequest) ProtoMessage() {}

func (x *RequestNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNovelRequest.ProtoReflect.Descriptor instead.
func (*RequestNovelRequest) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{10}
}

func (x *RequestNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RequestNovelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RequestNovelResponse) Reset() {
	*x = RequestNovelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_novel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNovelResponse) ProtoMessage() {}

func (x *RequestNovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_novel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNovelResponse.ProtoReflect.Descriptor instead.
func (*RequestNovelResponse) Descriptor() ([]byte, []int) {
	return file_protocol_novel_proto_rawDescGZIP(), []int{11}
}

func (x *RequestNovelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protocol_novel_proto protoreflect.FileDescriptor

var file_protocol_novel_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x22, 0x1c, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x9a,
	0x01, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x09,
	0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12, 0x29, 0x0a, 0x05, 0x6e, 0x6f, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6e,
	0x6f, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x62, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x62, 0x43, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x2e, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x73, 0x22, 0x54, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x4f, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x5f, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x4e, 0x6f, 0x76, 0x65,
	0x6c, 0x52, 0x05, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x22, 0x3d, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x42, 0x79, 0x22, 0x40, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4e,
	0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e,
	0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x4e, 0x6f, 0x76, 0x65,
	0x6c, 0x52, 0x06, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x95, 0x02, 0x0a, 0x0b, 0x4e, 0x6f, 0x76,
	0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x15, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e, 0x6f, 0x76,
	0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c,
	0x12, 0x16, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c,
	0x12, 0x17, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x6f, 0x76, 0x65,
	0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_novel_proto_rawDescOnce sync.Once
	file_protocol_novel_proto_rawDescData = file_protocol_novel_proto_rawDesc
)

func file_protocol_novel_proto_rawDescGZIP() []byte {
	file_protocol_novel_proto_rawDescOnce.Do(func() {
		file_protocol_novel_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_novel_proto_rawDescData)
	})
	return file_protocol_novel_proto_rawDescData
}

var file_protocol_novel_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protocol_novel_proto_goTypes = []interface{}{
	(*Author)(nil),               // 0: novel.Author
	(*Chapter)(nil),              // 1: novel.Chapter
	(*PartialNovel)(nil),         // 2: novel.PartialNovel
	(*FullNovel)(nil),            // 3: novel.FullNovel
	(*GetBookRequest)(nil),       // 4: novel.GetBookRequest
	(*GetBookResponse)(nil),      // 5: novel.GetBookResponse
	(*GetNovelRequest)(nil),      // 6: novel.GetNovelRequest
	(*GetNovelResponse)(nil),     // 7: novel.GetNovelResponse
	(*ListNovelRequest)(nil),     // 8: novel.ListNovelRequest
	(*ListNovelResponse)(nil),    // 9: novel.ListNovelResponse
	(*RequestNovelRequest)(nil),  // 10: novel.RequestNovelRequest
	(*RequestNovelResponse)(nil), // 11: novel.RequestNovelResponse
}
var file_protocol_novel_proto_depIdxs = []int32{
	2,  // 0: novel.FullNovel.novel:type_name -> novel.PartialNovel
	1,  // 1: novel.FullNovel.chapters:type_name -> novel.Chapter
	1,  // 2: novel.GetBookRequest.chapter:type_name -> novel.Chapter
	3,  // 3: novel.GetNovelResponse.novel:type_name -> novel.FullNovel
	2,  // 4: novel.ListNovelResponse.novels:type_name -> novel.PartialNovel
	4,  // 5: novel.NovelServer.GetBook:input_type -> novel.GetBookRequest
	6,  // 6: novel.NovelServer.GetNovel:input_type -> novel.GetNovelRequest
	8,  // 7: novel.NovelServer.ListNovel:input_type -> novel.ListNovelRequest
	10, // 8: novel.NovelServer.RequestNovel:input_type -> novel.RequestNovelRequest
	5,  // 9: novel.NovelServer.GetBook:output_type -> novel.GetBookResponse
	7,  // 10: novel.NovelServer.GetNovel:output_type -> novel.GetNovelResponse
	9,  // 11: novel.NovelServer.ListNovel:output_type -> novel.ListNovelResponse
	11, // 12: novel.NovelServer.RequestNovel:output_type -> novel.RequestNovelResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_novel_proto_init() }
func file_protocol_novel_proto_init() {
	if File_protocol_novel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_novel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chapter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialNovel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullNovel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNovelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_novel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNovelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_novel_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetNovelRequest_Id)(nil),
		(*GetNovelRequest_Title)(nil),
	}
	file_protocol_novel_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_novel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_novel_proto_goTypes,
		DependencyIndexes: file_protocol_novel_proto_depIdxs,
		MessageInfos:      file_protocol_novel_proto_msgTypes,
	}.Build()
	File_protocol_novel_proto = out.File
	file_protocol_novel_proto_rawDesc = nil
	file_protocol_novel_proto_goTypes = nil
	file_protocol_novel_proto_depIdxs = nil
}
